---
include-in-header: header.html
output-file: ".Survey-2026-Employee-Interactive"
---

```{r}
#| include: false

library(tidyverse)
```

```{r}
#| label: dict
#| include: false

dict <- read_csv(".data/dictionary-2026-09-04.csv") |>
  janitor::clean_names() |> 
  select(
    field_name = variable_field_name,
    form_name,
    field_type,
    field_label,
    choices = choices_calculations_or_slider_labels
  ) |>
  filter_out(
    form_name == "national_workforce_employer_survey" |
    field_type %in% c("descriptive", "text", "notes")
  ) |>
  mutate(
    form_name = form_name |> replace_values(
      "form_1" ~ "employee_1",
      "section_a2_role_workforce_context_35009f" ~ "employee_2_1",
      "section_a2_role_workforce_context" ~ "employee_2_2",
      "section_c_retention_burnout_career_intentions" ~ "employee_2_3"
    ),
    choices = choices |> replace_when(
      field_type == "yesno" ~ "0, No | 1, Yes"
    )
  )

columns_employee_single_select <- dict |>
  filter_out(field_type == "checkbox") |> 
  pull(field_name)

columns_employee_multi_select <- dict |>
  filter(field_type == "checkbox") |> 
  pull(field_name)
```

```{r}
#| label: choices
#| include: false

get_choices_as_tibble <- function(column) {
  matrix <- dict |> 
    filter(field_name == column) |>
    pull(choices) |>
    str_split_1(" \\| ") |>
    str_split_fixed(", ", n = 2)
  tibble(
    !!column := matrix[ ,1] |> as.numeric(),
    category = matrix[ ,2]
  )
}

choices <- dict |>
  pull(field_name) |>
  set_names() |>
  map(get_choices_as_tibble)
```

```{r}
#| label: employee
#| include: false

# import
employee <- read_csv(".data/data-2026-09-02-1114.csv") |>
  filter(
    redcap_event_name == "event_1_arm_1",
    landing_page_complete == 2
  ) |>
  rename(
    "employee_1_complete" = "form_1_complete",
    "employee_2_1_complete" = "section_a2_role_workforce_context_35009f_complete",
    "employee_2_2_complete" = "section_a2_role_workforce_context_complete",
    "employee_2_3_complete" = "section_c_retention_burnout_career_intentions_complete"
  ) |> 
  select(
    record_id,
    all_of(columns_employee_single_select),
    contains(columns_employee_multi_select |> paste0("___")),
    starts_with("employee_")
  )

# clean
employee <- employee |>
  select(-ends_with("999")) |> # "PNTA"
  mutate(
    across(-record_id, \(x)
      na_if(x, 999) # "PNTA"
    ),
    across(c(career_ladder, career_support, career_workload, career_crdtl), \(x)
      na_if(x, 6) # "N/A"
    ),
    across(c(num_range("unemp_jobsearch___", 1:5)), \(x) 
      replace_when(x, unemp_jobsearch___6 == 1 ~ 0) # equivalent to "N/A"
    )
  ) |>
  select(-unemp_jobsearch___6) # equivalent to "N/A"
```

```{r}
#| label: data-from-R
#| include: false

ojs_define(
  employee_from_r = employee,
  dict_from_r = dict,
  columns_employee_single_select_from_r = columns_employee_single_select,
  columns_employee_multi_select_from_r = columns_employee_multi_select,
  choices_from_r = choices
)
```

```{ojs data-to-OJS}

employee = aq.table(employee_from_r)
dict = aq.table(dict_from_r)
columns_employee_single_select = columns_employee_single_select_from_r
columns_employee_multi_select = columns_employee_multi_select_from_r
choices = Object.fromEntries(
  Object.entries(choices_from_r).map(([k, v]) => [k, aq.table(v)])
)
```

```{ojs get-question}

function get_question(column) {
  return dict
    .filter(aq.escape(d => d.field_name === column))
    .array("field_label")[0]
}
```

```{ojs pivot-longer}

function pivot_longer_1(data, column) {
  return data
    .select("record_id", aq.startswith(column + "___"))
    .fold(aq.not("record_id"))
    // .select(aq.startswith(column))
    // .fold(aq.all())
    .derive({ key: aq.escape(d => aq.op.replace(d.key, column + "___", "")) })
    .filter(d => d.value === 1)
    .rename({ key: column })
    .derive({ [column]: aq.escape(d => aq.op.parse_int(d[column], 10)) })
}
```

```{ojs make-objects}

function make_objects_1(data, column) {
  const section_complete = dict
    .filter(aq.escape(d => d.field_name === column))
    .array("form_name")[0] + "_complete"
  return data
    .filter(aq.escape(d => d[section_complete] === 2))
    .select(column)
    .filter(aq.escape(d => d[column] !== null))
    .groupby(column)
    .count()
    .derive({ "pct": d => aq.op.round(d.count / aq.op.sum(d.count) * 100) })
    .join_left(choices[column], column)
    .relocate("category", { before: "count" })
    .orderby(column)
    .objects()
}

function make_objects_2(data, column) {
  const section_complete = dict
    .filter(aq.escape(d => d.field_name === column))
    .array("form_name")[0] + "_complete"
  const data_section_complete = data
    .filter(aq.escape(d => d[section_complete] === 2))
  const data_reshaped = pivot_longer_1(data_section_complete, column)
  const n = data_reshaped
    .dedupe("record_id")
    .numRows()
  return data_reshaped
    .select(column)
    .filter(aq.escape(d => d[column] !== null))
    .groupby(column)
    .count()
    .derive({ "pct": aq.escape(d => aq.op.round(d.count / n * 100)) })
    .join_left(choices[column], column)
    .relocate("category", { before: "count" })
    .orderby(column)
    .objects()
}
```

```{ojs make-table}

function make_table(make_objects, data, column) {
  const table = html`<table class="row-border order-column"></table>`
  new DataTable(table, {
    data: make_objects(data, column),
    columns: [
      { data: column, title: column, width: "28%" },
      { data: "category", title: "category" },
      { data: "count", title: "count", width: "11%" },
      { data: "pct", title: "%", width: "6%", orderable: false }
    ],
    order: [[2, "desc"]],
    paging: false,
    searching: false,
    lengthChange: false,
    info: false,
    autoWidth: false,
    language: { emptyTable: "No matching records found" }
  })
  return html`<div>${table}</div>`
}
```

```{ojs make-input}

function make_input_1(data, column) {
  return Inputs.checkbox(
    data
      .filter(aq.escape(d => d[column] !== null))
      .dedupe(column)
      .orderby(column)
      .array(column)
  )
}

function make_input_2(data, column) {
  return Inputs.checkbox(
    pivot_longer_1(data, column)
      .dedupe(column)
      .orderby(column)
      .array(column)
  )
}
```

```{r}
#| label: inputs
#| output: asis

cat("```{ojs inputs}\n")
cat("inputs = ({\n")
dict |> 
  str_glue_data("  {field_name}: input_{field_name}") |> 
  cat(sep = ",\n")
cat("})\n")
cat("```\n")
```

```{ojs filtered-employee}

filtered_employee = employee.filter(aq.escape(d => 
  columns_employee_single_select.every(column => 
    inputs[column].length === 0 || 
    inputs[column].includes(d[column])
  ) &&
  columns_employee_multi_select.every(column => 
    inputs[column].length === 0 || 
    inputs[column].some(n => d[column + "___" + n] === 1)
  )
))

// .some() for OR, union
// .every() for AND, intersection
```

```{r}
#| label: write-ojs

source("write-ojs.R")
chunks <- c(
  set_names(columns_employee_single_select) |> 
    map(\(x) write_ojs(1, x)),
  set_names(columns_employee_multi_select) |> 
    map(\(x) write_ojs(2, x))
)
```

## Employee

### Demographics

:::::::::: panel-tabset
#### Gender

```{r}
#| output: asis

chunks$demog_gen
```

#### Age

```{r}
#| output: asis

chunks$demog_age
```

#### Location

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_locat
```

##### 2

```{r}
#| output: asis

chunks$demog_locat_live
```
:::

#### Indigenous

```{r}
#| output: asis

chunks$demog_indig
```

#### Minority

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_minority
```

##### 2

```{r}
#| output: asis

chunks$demog_popu
```
:::

#### Disability

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_disability
```

##### 2

```{r}
#| output: asis

chunks$demog_disability_typ
```
:::

#### Language

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_lang
```

##### 2

```{r}
#| output: asis

chunks$demog_language_work
```
:::

#### Education

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_iehp
```

##### 2

```{r}
#| output: asis

chunks$demog_edu
```

##### 3

```{r}
#| output: asis

chunks$demog_cr
```

##### 4

```{r}
#| output: asis

chunks$demog_cr_cert
```
:::

#### Employment

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_employ_typ
```

##### 2

```{r}
#| output: asis

chunks$demog_sector
```

##### 3

```{r}
#| output: asis

chunks$demog_commun
```

##### 4

```{r}
#| output: asis

chunks$demog_role
```
:::

#### Experience

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$demog_wrk_yr
```

##### 2

```{r}
#| output: asis

chunks$demog_current_wrk
```
:::
::::::::::

### Perspectives

:::::::: panel-tabset
#### Role context

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$role_jobmatch
```

##### 2

```{r}
#| output: asis

chunks$role_compensation
```

##### 3

```{r}
#| output: asis

chunks$role_overtime
```

##### 4

```{r}
#| output: asis

chunks$role_complex
```
:::

#### Career advancement

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$career_ladder
```

##### 2

```{r}
#| output: asis

chunks$career_support
```

##### 3

```{r}
#| output: asis

chunks$career_workload
```

##### 4

```{r}
#| output: asis

chunks$career_crdtl
```
:::

#### Team capacity

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$ret_max
```

##### 2

```{r}
#| output: asis

chunks$ret_struggle
```
:::

#### Job change

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$career_leav
```

##### 2

```{r}
#| output: asis

chunks$career_int
```
:::

#### Unemployed

::: panel-tabset
##### 1

```{r}
#| output: asis

chunks$unemp_challeng
```

##### 2

```{r}
#| output: asis

chunks$unemp_miss
```

##### 3

```{r}
#| output: asis

chunks$unemp_jobsearch
```
:::
::::::::
