---
output-file: "Survey-2026-Employer"
format:
  typst:
    toc-title: "Employer"
---

```{r}
#| include: false

library(tidyverse)
source("source-qmd.R")
source_qmd("1-functions.qmd")
source_qmd("2-dict.qmd")
source_qmd("4-data-employer.qmd")
```

::: {.content-hidden unless-format="html"}
# Employer
:::

## Characteristics

::: panel-tabset
### 1

```{r}
#| label: emp-org-scale

employer$emp_org_scale |>
  ggplot_1() +
  scale_x_discrete(
    labels = choices$emp_org_scale |>
      str_remove_all("^.*: | -.*$")
  ) +
  labs(
    title = get_question("emp_org_scale") |>
      str_wrap(55)
  )
```

{{< pagebreak >}}

### 2

```{r}
#| label: emp-org-typ

employer$emp_org_typ |>
  mutate(emp_org_typ = emp_org_typ |> fct_reorder(-count)) |> 
  ggplot_1() +
  scale_x_discrete(
    labels = choices$emp_org_typ |>
      str_remove(":.*$") |>
      str_replace("/", " / ") |>
      str_wrap(15)
  ) +
  labs(title = get_question("emp_org_typ"))
```

### 3

```{r}
#| label: emp-org-prov

employer$emp_org_prov |>
  mutate(
    emp_org_prov = emp_org_prov |> 
      fct_reorder(-count) |> 
      fct_relevel("1", after = Inf)
  ) |>
  ggplot_1() +
  scale_x_discrete(
    labels = c(
      "1" = "National /\nPan-Canadian",
      "2" = "AB",
      "3" = "BC",
      "4" = "MB",
      "5" = "NB",
      "6" = "NL",
      "7" = "QC",
      "8" = "NS",
      "9" = "ON",
      "10" = "PE",
      "11" = "SK",
      "12" = "NT",
      "13" = "NU",
      "14" = "YT"
    )
  ) +
  labs(title = "Where in Canada does your organization conduct Clinical Research operations?")
```

### 4

```{r}
#| label: emp-site

employer$emp_site |>
  ggplot_1() +
  scale_x_discrete(
    labels = choices$emp_site |>
      c("4" = "Rural/Northern") |>
      str_remove(" \\(.*\\)")
  ) +
  labs(title = get_question("emp_site"))
```

### 5

```{r emp-active-trial}

employer_2$emp_active_trial |> 
  mutate(emp_active_trial = case_when(
    emp_active_trial < 11 ~ "1-10",
    emp_active_trial < 51 ~ "11-50",
    emp_active_trial < 201 ~ "51-200",
    .default = "> 200"
  )) |>
  count(emp_active_trial) |> 
  mutate(
    pct = count / sum(count),
    emp_active_trial = emp_active_trial |> 
      fct_relevel("> 200", after = Inf)
  ) |> 
  ggplot_1() +
  labs(
    title = get_question("emp_active_trial") |> 
      str_wrap(55)
  )
```

### 6

```{r emp_role_host}

employer_2$emp_role_host |> 
  mutate(emp_role_host = case_when(
    emp_role_host < 11 ~ "1-10",
    emp_role_host < 101 ~ "11-100",
    emp_role_host < 1001 ~ "101-1000",
    .default = "> 1000"
  )) |> 
  count(emp_role_host) |> 
  mutate(
    pct = count / sum(count),
    emp_role_host = emp_role_host |> 
      fct_relevel("101-1000", "> 1000", after = Inf)
  ) |>
  ggplot_1() +
  labs(
    title = get_question("emp_role_host") |> 
      str_remove(" \\(.*\\)")
  )
```

### 7

```{r emp_perm_role}

employer_2$emp_perm_role |> 
  mutate(emp_perm_role = case_when(
    emp_perm_role < 1 ~ "0",
    emp_perm_role < 11 ~ "1-10",
    emp_perm_role < 101 ~ "11-100",
    .default = "> 100"
  )) |> 
  count(emp_perm_role) |> 
  mutate(
    pct = count / sum(count),
    emp_perm_role = emp_perm_role |> 
      fct_relevel("> 100", after = Inf)
  ) |>
  ggplot_1() +
  labs(
    title = get_question("emp_perm_role") |>
      str_replace("\\[", "\n(") |> 
      str_replace("\\]", ")")
  )
```

### 8

```{r emp-vacant-post}

employer_2$emp_vacant_post |>
  mutate(emp_vacant_post = case_when(
    emp_vacant_post == "0" ~ "No",
    emp_vacant_post != "0" ~ "Yes"
  )) |>
  count(emp_vacant_post) |>
  mutate(pct = count / sum(count)) |>
  ggplot_1() +
  labs(
    title = "Are there currently any Clinical Research positions within your organization that are unfilled and actively being recruited for?" |> 
      str_wrap(70)
  )
```

### 9

```{r}
#| label: emp-certif

employer$emp_certif |>
  mutate(
    emp_certif = emp_certif |>
      fct_expand("4", after = 3)
  ) |>
  ggplot_1(drop_empty = FALSE) +
  scale_x_discrete(
    labels = choices$emp_certif |> 
      str_replace(" nor ", "/") |> 
      str_replace("clinical research staff.", "Clinical Research staff") |>
      str_wrap(30),
    drop = FALSE
  ) +
  labs(
    title = get_question("emp_certif") |>
      str_remove(" %") |>
      str_wrap(75)
  )
```
:::

{{< pagebreak >}}

## Trends

::: panel-tabset
### 1

```{r emp-applic}

employer_2$emp_applic |> 
  mutate(emp_applic = case_when(
    emp_applic < 11 ~ "0-10",
    emp_applic < 51 ~ "11-50",
    .default = "> 50"
  )) |> 
  count(emp_applic) |> 
  mutate(
    pct = count / sum(count),
    emp_applic = emp_applic |> fct_relevel("> 50", after = Inf)
  ) |>
  ggplot_1() +
  labs(
    title = get_question("emp_applic") |> 
      str_match("how.*role\\?") |> 
      str_replace("how", "How")
  )
```

### 2

```{r}
#| label: emp-applic-trend

employer$emp_applic_trend |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_applic_trend) +
  labs(title = get_question("emp_applic_trend"))
```

{{< pagebreak >}}

### 3

```{r}
#| label: emp-post-fill

employer$emp_post_fill |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_post_fill) +
  labs(
    title = get_question("emp_post_fill") |>
      str_remove(" \\(.*\\)") |>
      str_wrap(84)
  )
```

### 4

```{r}
#| label: emp-indep

employer$emp_indep |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_indep) +
  labs(
    title = get_question("emp_indep") |>
      str_wrap(60)
  )
```
:::

{{< pagebreak >}}

## Turnover

::: panel-tabset
### 1

```{r}
#| label: emp-turnover-rate

employer$emp_turnover_rate |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_turnover_rate) +
  labs(
    title = get_question("emp_turnover_rate") |>
      str_wrap(58)
  )
```

{{< pagebreak >}}

### 2

```{r}
#| label: emp-resig

employer$emp_resig |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_resig) +
  labs(title = get_question("emp_resig"))
```

### 3

```{r}
#| label: emp-termi

employer$emp_termi |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_termi) +
  labs(
    title = get_question("emp_termi") |>
      str_replace("/", ", ")
  )
```
:::

{{< pagebreak >}}

## Perspectives

::: panel-tabset
### 1

```{r}
#| label: emp-limit-trial

employer$emp_limit_trial |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_limit_trial) +
  labs(title = get_question("emp_limit_trial"))
```

{{< pagebreak >}}

### 2

```{r}
#| label: emp-demand

employer$emp_demand |>
  mutate(
    emp_demand = emp_demand |> 
      fct_expand("1", after = 0)
  ) |>
  ggplot_1(drop_empty = FALSE) +
  scale_x_discrete(
    drop = FALSE,
    labels = choices$emp_demand
  ) +
  labs(
    title = get_question("emp_demand") |>
      str_wrap(50)
  )
```

### 3

```{r}
#| label: emp-shortage

employer$emp_shortage |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_shortage) +
  labs(title = get_question("emp_shortage"))
```

### 4

```{r}
#| label: emp-missed-trial

employer$emp_missed_trial |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_missed_trial) +
  labs(title = get_question("emp_missed_trial"))
```

### 5

```{r}
#| label: emp-strategy

employer$emp_strategy |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_strategy) +
  labs(
    title = get_question("emp_strategy") |> 
      str_wrap(85)
  )
```
:::

{{< pagebreak >}}

## Barriers to recruiting qualified staff

::: panel-tabset
### 1

```{r}
#| label: emp-sal

employer$emp_sal |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_sal) +
  labs(
    title = get_question("emp_sal") |>
      str_replace(": ", ":\n")
  )
```

{{< pagebreak >}}

### 2

```{r}
#| label: emp-qual

employer$emp_qual |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_qual) +
  labs(
    title = get_question("emp_qual") |>
      str_replace(": ", ":\n") |>
      str_remove(" or ")
  )
```

### 3

```{r}
#| label: emp-contr

employer$emp_contr |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_contr) +
  labs(
    title = get_question("emp_contr") |>
      str_replace(": ", ":\n") |>
      str_replace("roles", "roles\\.")
  )
```

### 4

```{r}
#| label: emp-geo

employer$emp_geo |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_geo) +
  labs(
    title = get_question("emp_geo") |>
      str_replace(": ", ":\n")
  )
```

### 5

```{r}
#| label: emp-pipe

employer$emp_pipe |>
  ggplot_1() +
  scale_x_discrete(labels = choices$emp_pipe) +
  labs(
    title = get_question("emp_pipe") |>
      str_replace(": ", ":\n") |>
      str_replace_all("\"", "")
  )
```

### 6

```{r}
#| label: emp-reput

employer$emp_reput |>
  mutate(
    emp_reput = emp_reput |>
      fct_expand("4", after = 3)
  ) |>
  ggplot_1(drop_empty = FALSE) +
  scale_x_discrete(
    drop = FALSE,
    labels = choices$emp_reput
  ) +
  labs(
    title = get_question("emp_reput") |>
      str_replace(": ", ":\n")
  )
```

### 7

```{r}
#| label: barriers

employer_1 |>
  select(emp_sal, emp_qual, emp_contr, emp_geo, emp_pipe, emp_reput) |>
  drop_na() |> 
  ggstats::gglikert(
    variable_labels = c(
      emp_sal = "Salary / Benefits",
      emp_qual = "Candidate Quality",
      emp_contr = "Contract Instability",
      emp_geo = "Geography",
      emp_pipe = "Internal Pipeline",
      emp_reput = "Workload Reputation"
    ),
    y_label_wrap = 15,
    sort = "ascending",
    cutoff = 1
  ) +
  scale_x_continuous(
    breaks = seq(-0.25, 0.75, 0.25),
    labels = \(x) scales::label_percent()(abs(x))
  ) +
  scale_fill_viridis_d(
    option = "viridis", 
    labels = choices$emp_sal
  ) +
  labs(
    title = "Barriers to recruiting qualified staff",
    subtitle = paste0("n = ", n_respondents$emp_sal)
  ) +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_text(hjust = 0.5),
    legend.key.size = unit(1, "lines"),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
```
:::
