---
include-in-header: header.html
output-file: ".Survey-2026-Employer-Interactive"
---

```{r library}
#| include: false

library(tidyverse)
source("write-ojs.R")
```

```{r dict}
#| include: false

dict <- read_csv(".data/dictionary-2026-09-04.csv") |>
  janitor::clean_names() |> 
  select(
    field_name = variable_field_name,
    form_name,
    field_type,
    field_label,
    choices = choices_calculations_or_slider_labels
  ) |>
  filter(
    form_name == "national_workforce_employer_survey",
    field_type %in% c("radio", "yesno", "dropdown", "checkbox") |
    field_name %in% c(
      "emp_active_trial", 
      "emp_applic", 
      "emp_role_host",
      "emp_perm_role",
      "emp_vacant_post"
    )
  ) |>
  mutate(choices = choices |> replace_when(
    field_type == "yesno" ~ "0, No | 1, Yes",
    field_name == "emp_active_trial" ~ "1, 1-10 | 2, 11-50 | 3, 51-200 | 4, > 200",
    field_name == "emp_applic" ~ "1, 0-10 | 2, 11-50 | 3, > 50",
    field_name == "emp_role_host" ~ "1, 1-10 | 2, 11-100 | 3, 101-1000 | 4, > 1000",
    field_name == "emp_perm_role" ~ "1, 0 | 2, 1-10 | 3, 11-100 | 4, > 100",
    field_name == "emp_vacant_post" ~ "1, No | 2, Yes"
  ))

columns_single_select <- dict |>
  filter_out(field_type == "checkbox") |> 
  pull(field_name)

columns_multi_select <- dict |>
  filter(field_type == "checkbox") |> 
  pull(field_name)
```

```{r choices}
#| include: false

get_choices_as_tibble <- function(column) {
  matrix <- dict |> 
    filter(field_name == column) |>
    pull(choices) |>
    str_split_1(" \\| ") |>
    str_split_fixed(", ", n = 2)
  tibble(
    !!column := matrix[ ,1] |> as.numeric(),
    category = matrix[ ,2]
  )
}

choices <- dict |>
  pull(field_name) |>
  set_names() |>
  map(get_choices_as_tibble)
```

```{r data-import}
#| include: false

data <- read_csv(".data/data-2026-09-02-1114.csv") |>
  filter(
    redcap_event_name == "event_2_arm_2",
    national_workforce_employer_survey_complete == 2
  ) |> 
  select(
    where(\(x) any(!is.na(x))),
    -c(
      redcap_event_name,
      landing_page_timestamp,
      landing_page_complete,
      national_workforce_employer_survey_timestamp,
      national_workforce_employer_survey_complete,
      starts_with("language"),
      emp_org_typ_otr,
      emp_org_strategy
    )
  )
```

```{r data-clean}
#| include: false

data <- data |> mutate(
  
  emp_active_trial = emp_active_trial |>
    replace_values(
      "3-4" ~ "3",
      "10-15" ~ "10",
      "~700" ~ "700",
      "over 100" ~ "100",
      "789 actuellement" ~ "789",
      "donnée inconnue" ~ NA,
      "pour ma division: 30" ~ NA
    ) |>
    as.numeric(),
  emp_active_trial = case_when(
    emp_active_trial < 11 ~ 1,
    emp_active_trial < 51 ~ 2,
    emp_active_trial < 201 ~ 3,
    emp_active_trial > 200 ~ 4
  ),
  
  emp_role_host = emp_role_host |>
    replace_values(
      "18-25" ~ "21",
      "~350" ~ "350",
      "60 FTE" ~ "60",
      "over 100" ~ "101",
      "600 actuellement" ~ "600",
      "+120 most are FTE" ~ "120",
      "2 FTE, 1 Casual hourly" ~ "2",
      "2 FTE, 4 contractual" ~ "2",
      "around 9 different roles" ~ "9",
      "Operations Director, Scientific Director, Project Managers, Office Assistant, Multimedia Coordinator, Writing coordinator" ~ "7",
      "pour ma division: 24" ~ NA
    ) |>
    as.numeric(),
  emp_role_host = case_when(
    emp_role_host < 11 ~ 1,
    emp_role_host < 101 ~ 2,
    emp_role_host < 1001 ~ 3,
    emp_role_host > 1000 ~ 4
  ),
  
  emp_perm_role = emp_perm_role |>
    replace_values(
      "2 FTE" ~ "2",
      "environ 50" ~ "50",
      "over 100" ~ "101",
      "same" ~ "120",
      "Unknown" ~ NA,
      "pour ma division: 20" ~ NA
    ) |>
    as.numeric(),
  emp_perm_role = case_when(
    emp_perm_role < 1 ~ 1,
    emp_perm_role < 11 ~ 2,
    emp_perm_role < 101 ~ 3,
    emp_perm_role > 100 ~ 4
  ),
  
  emp_vacant_post = emp_vacant_post |>
    replace_values(
      "between 5-10" ~ "7",
      "none" ~ NA,
      "None" ~ NA,
      "Unknown" ~ NA
    ) |>
    as.numeric(),
  emp_vacant_post = case_when(
    emp_vacant_post == 0 ~ 1,
    emp_vacant_post > 0 ~ 2
  ),
  
  emp_applic = emp_applic |>
    replace_values(
      "2-3" ~ "2",
      "4-5" ~ "4",
      "30-50" ~ "40",
      ">50" ~ "51",
      "around 3-4 applications" ~ "3",
      "Nurses: 15-20, CRC: 40-50" ~ "31",
      "it depends on the position varies from less than 10 to more than 50" ~ "30",
      "hiring is usually targeted" ~ NA
    ) |>
    as.numeric(),
  emp_applic = case_when(
    emp_applic < 11 ~ 1,
    emp_applic < 51 ~ 2,
    emp_applic > 50 ~ 3
  )

)
```

```{r data-from-R}
#| include: false

ojs_define(
  dict_from_r = dict,
  columns_single_select_from_r = columns_single_select,
  columns_multi_select_from_r = columns_multi_select,
  choices_from_r = choices,
  data_from_r = data
)
```

```{ojs data-to-OJS}

dict = aq.table(dict_from_r)
columns_single_select = columns_single_select_from_r
columns_multi_select = [].concat(columns_multi_select_from_r)
choices = Object.fromEntries(
  Object.entries(choices_from_r).map(([k, v]) => [k, aq.table(v)])
)
data = aq.table(data_from_r)
```

```{ojs get-question}

function get_question(column) {
  return dict
    .filter(aq.escape(d => d.field_name === column))
    .array("field_label")[0]
}
```

```{ojs pivot-longer}

function pivot_longer_1(data, column) {
  return data
    .select("record_id", aq.startswith(column + "___"))
    .fold(aq.not("record_id"))
    // .select(aq.startswith(column))
    // .fold(aq.all())
    .derive({ key: aq.escape(d => aq.op.replace(d.key, column + "___", "")) })
    .filter(d => d.value === 1)
    .rename({ key: column })
    .derive({ [column]: aq.escape(d => aq.op.parse_int(d[column], 10)) })
}
```

```{ojs make-objects}

function make_objects_1(data, column) {
  return data
    .select(column)
    .filter(aq.escape(d => d[column] !== null))
    .groupby(column)
    .count()
    .derive({ "pct": d => aq.op.round(d.count / aq.op.sum(d.count) * 100) })
    .join_left(choices[column], column)
    .relocate("category", { before: "count" })
    .orderby(column)
    .objects()
}

function make_objects_2(data, column) {
  const data_reshaped = pivot_longer_1(data, column)
  const n = data_reshaped
    .dedupe("record_id")
    .numRows()
  return data_reshaped
    .select(column)
    .filter(aq.escape(d => d[column] !== null))
    .groupby(column)
    .count()
    .derive({ "pct": aq.escape(d => aq.op.round(d.count / n * 100)) })
    .join_left(choices[column], column)
    .relocate("category", { before: "count" })
    .orderby(column)
    .objects()
}
```

```{ojs make-table}

function make_table(make_objects, data, column) {
  const table = html`<table class="row-border order-column"></table>`
  new DataTable(table, {
    data: make_objects(data, column),
    columns: [
      { data: column, title: column, width: "28%" },
      { data: "category", title: "category" },
      { data: "count", title: "count", width: "11%" },
      { data: "pct", title: "%", width: "6%", orderable: false }
    ],
    order: [[2, "desc"]],
    paging: false,
    searching: false,
    lengthChange: false,
    info: false,
    autoWidth: false,
    language: { emptyTable: "No matching records found" }
  })
  return html`<div>${table}</div>`
}
```

```{ojs make-input}

function make_input_1(data, column) {
  return Inputs.checkbox(
    data
      .filter(aq.escape(d => d[column] !== null))
      .dedupe(column)
      .orderby(column)
      .array(column)
  )
}

function make_input_2(data, column) {
  return Inputs.checkbox(
    pivot_longer_1(data, column)
      .dedupe(column)
      .orderby(column)
      .array(column)
  )
}
```

```{r inputs}
#| output: asis

cat("```{ojs inputs}\n")
cat("inputs = ({\n")
dict |> 
  str_glue_data("  {field_name}: input_{field_name}") |> 
  cat(sep = ",\n")
cat("})\n")
cat("```\n")
```

```{ojs filtered-data}

filtered_data = data.filter(aq.escape(d => 
  columns_single_select.every(column => 
    inputs[column].length === 0 || 
    inputs[column].includes(d[column])
  ) &&
  columns_multi_select.every(column => 
    inputs[column].length === 0 || 
    inputs[column].some(n => d[column + "___" + n] === 1)
  )
))
```

```{r write-ojs}

source("write-ojs.R")
chunks <- c(
  set_names(columns_single_select) |> 
    map(\(x) write_ojs(1, x)),
  set_names(columns_multi_select) |> 
    map(\(x) write_ojs(2, x))
)
```

# Employer

## Characteristics

::: panel-tabset
### 1

```{r}
#| output: asis

chunks$emp_org_scale
```

### 2

```{r}
#| output: asis

chunks$emp_org_typ
```

### 3

```{r}
#| output: asis

chunks$emp_org_prov
```

### 4

```{r}
#| output: asis

chunks$emp_site
```

### 5

```{r}
#| output: asis

chunks$emp_active_trial
```

### 6

```{r}
#| output: asis

chunks$emp_role_host
```

### 7

```{r}
#| output: asis

chunks$emp_perm_role
```

### 8

```{r}
#| output: asis

chunks$emp_vacant_post
```

### 9

```{r}
#| output: asis

chunks$emp_certif
```
:::

## Trends

::: panel-tabset
### 1

```{r}
#| output: asis

chunks$emp_applic
```

### 2

```{r}
#| output: asis

chunks$emp_applic_trend
```

### 3

```{r}
#| output: asis

chunks$emp_post_fill
```

### 4

```{r}
#| output: asis

chunks$emp_indep
```
:::

## Turnover

::: panel-tabset
### 1

```{r}
#| output: asis

chunks$emp_turnover_rate
```

### 2

```{r}
#| output: asis

chunks$emp_resig
```

### 3

```{r}
#| output: asis

chunks$emp_termi
```
:::

## Perspectives

::: panel-tabset
### 1

```{r}
#| output: asis

chunks$emp_limit_trial
```

### 2

```{r}
#| output: asis

chunks$emp_demand
```

### 3

```{r}
#| output: asis

chunks$emp_shortage
```

### 4

```{r}
#| output: asis

chunks$emp_missed_trial
```

### 5

```{r}
#| output: asis

chunks$emp_strategy
```
:::

## Barriers to recruiting qualified staff

::: panel-tabset
### 1

```{r}
#| output: asis

chunks$emp_sal
```

### 2

```{r}
#| output: asis

chunks$emp_qual
```

### 3

```{r}
#| output: asis

chunks$emp_contr
```

### 4

```{r}
#| output: asis

chunks$emp_geo
```

### 5

```{r}
#| output: asis

chunks$emp_pipe
```

### 6

```{r}
#| output: asis

chunks$emp_reput
```
:::
